### ISSUE TITLE
Getting a crash whenever I try to launch server with craftplusplus

### ISSUE THREAD

**Issue by MadnessExpress** [Anon10W1z/CraftPlusPlus#3]
---- Minecraft Crash Report ----

**\* ATTENTION: detected classes with unsupported format ***
**\* DO NOT SUBMIT THIS CRASH REPORT TO FORGE ***

Contact authors of the following mods: 
  craft++

WARNING: coremods are present:
  NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
  NowWithRendering (redstonepaste-mc1.8-1.7.1.jar)
  CCCDeobfPlugin (unknown)
  CoreMod (Aroma1997Core-1.8-1.0.3.4.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 7/2/15 4:41 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: io.github.anon10w1z.craftPP.main.CraftPlusPlus
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:163)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:538)
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:355)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:438)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: io.github.anon10w1z.craftPP.main.CraftPlusPlus
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:60)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:445)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:507)
    ... 5 more
Caused by: java.lang.UnsupportedClassVersionError: io/github/anon10w1z/craftPP/main/CraftPlusPlus : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 32 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.8
    Operating System: Linux (amd64) version 3.10.23-xxxx-std-ipv6-64
    Java Version: 1.7.0_51, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1926028048 bytes (1836 MB) / 2058878976 bytes (1963 MB) up to 2058878976 bytes (1963 MB)
    JVM Flags: 2 total; -Xmx2048M -Xms2048M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1487 24 mods loaded, 24 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UC  mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UC  FML{8.0.99.99} [Forge Mod Loader](forge-1.8-11.14.3.1487-universal.jar) 
    UC  Forge{11.14.3.1487} [Minecraft Forge](forge-1.8-11.14.3.1487-universal.jar) 
    UC  Aroma1997Core{1.0.3.4} [Aroma1997Core](Aroma1997Core-1.8-1.0.3.4.jar) 
    UC  CodeChickenCore{1.0.5.36} [CodeChicken Core](minecraft.jar) 
    UC  NotEnoughItems{1.0.5.104} [Not Enough Items](NotEnoughItems-1.8-1.0.5.104-universal.jar) 
    UC  Aroma1997CoreHelper{1.0.3.4} [Aroma1997Core|Helper](Aroma1997Core-1.8-1.0.3.4.jar) 
    UC  Baubles{1.1.1.0} [Baubles](Baubles-1.8-1.1.1.0.jar) 
    UC  BetterChests{1.2.0.0} [BetterChests](BetterChests-1.8-1.2.0.0.jar) 
    UC  C4Lib{1.0.0} [C4Lib](C4Lib-1.8-1.0.0-universal.jar) 
    UC  MemoryCleaner{1.0} [Memory Cleaner](MemoryCleaner-1.4-mc.1.8.jar) 
    UC  me{1.3.2.1} [More Enchantments](MoreEnchantments-1.8-1.3.2.1.jar) 
    UC  AencEx{0.0.1} [AencEx](MoreEnchantments-1.8-1.3.2.1.jar) 
    UC  moreplayermodels{1.8.0_beta} [MorePlayerModels](MorePlayerModels_1.8.0_beta.jar) 
    UC  Morpheus{1.8-2.0.40} [Morpheus](Morpheus-1.8-2.0.40.jar) 
    UC  cfm{3.4.7} [�9MrCrayfish's Furniture Mod](MrCrayfishFurnitureModv3.4.7-build5%281.8%29.jar) 
    UC  obsidianutils{v1.0} [Obsidian Utilities](ObsidianUtilities-1.0.jar) 
    UC  pcb{1.4} [Portable Craft Bench](portablecraftbench-1.8-1.4.jar) 
    UC  redstonepaste{1.7.1} [Redstone Paste](redstonepaste-mc1.8-1.7.1.jar) 
    UC  Roguelike{1.3.6} [Roguelike Dungeons](RoguelikeDungeons-1.8-1.3.6.jar) 
    UC  Talismans 2{2.1.2} [Talismans 2](Talismans2-1.8-2.1.2.jar) 
    UC  utilityworlds{1.0.7} [Utility Worlds](UtilityWorlds-1.8_1.0.7.jar) 
    UC  worldedit{6.1} [WorldEdit](worldedit-forge-mc1.8-6.1.jar) 
    UE  craft++{3.2} [Craft++](CraftPlusPlus-3.2.jar) 
    Loaded coremods (and transformers): 
NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
  codechicken.nei.asm.NEITransformer
NowWithRendering (redstonepaste-mc1.8-1.7.1.jar)
  net.fybertech.nwr.NowWithRendering
CCCDeobfPlugin (unknown)

CoreMod (Aroma1997Core-1.8-1.0.3.4.jar)

CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  codechicken.core.asm.InterfaceDependancyTransformer
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
    Profiler Position: N/A (disabled)
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by Anon10W1z** [comment]
Working on it.

**Comment by Anon10W1z** [comment]
Fixed as of 0c9988e.
